Enable Server to place encrypted inputs request..
marlinprotocol/Avail_server pull request #2
Opened 2024-08-27 08:34 UTC by akshay111meher

checks whether any encrypted request received in provable or not using IVS, if provable request is placed

2024-08-27 08:35 UTC, akshay111meher commented
The code is bloated, fix this..
Avoid of use `any` unless and until **very very important**

2024-08-28 07:51 UTC, KalpitaMandal approved these changes
Tested for the happy path for `/proveTx` and was able to get proof

2024-08-28 07:55 UTC, KalpitaMandal requested changes

2024-08-28 07:55 UTC, KalpitaMandal commented on README.md
>  #### Creating ask and getting execution
Add steps for the encrypted inputs in the README

2024-09-11 06:45 UTC, KalpitaMandal approved these changes

2024-09-12 11:58 UTC, merged